### ISSUE TITLE
Error installing: "Fail to load plugin descriptor from file HakunaMatata.jar"

### ISSUE THREAD

**Issue by malenalbc** [cesards/HakunaMatataIntelliJPlugin#1]
### 1. Steps taken to see the issue.

On Android Studio 2.1.2:
Go to File > Preferences > Plugins.
Click _Install plugin from disk_.
Search for _HakunaMatata.jar_ and click on it.
Error message appears.
### 2. Observed behavior.

![screen shot 2016-06-28 at 10 02 44](https://cloud.githubusercontent.com/assets/4637279/16408279/4abc3356-3d18-11e6-8d88-c0480323d12f.png)
### 3. Expected behavior.

Install the plugin.
### 4. Device and OS.

Android Studio 2.1.2 on Mac OSX 10.11.12
### 5. Can you reproduce it? How often: 100% of the time, 50%, just.. sometimes?

100%

**Comment by cesards** [comment]
Fixed: https://github.com/cesards/HakunaMatataIntelliJPlugin/commit/0f892e7a03786eb146406621ff2b9f83dfae80c1
