### ISSUE TITLE
Point to this GitHub repo in the project description

### ISSUE THREAD

**Issue by rocboronat** [cesards/HakunaMatataIntelliJPlugin#2]
The README.md of the project is great. Don't hesitate to link it in the plugin description embedded in IntelliJ.

![image](https://cloud.githubusercontent.com/assets/456499/16415721/edcb17c6-3d3e-11e6-8394-6ea7df823357.png)

**Comment by cesards** [comment]
Done!
https://github.com/cesards/HakunaMatataIntelliJPlugin/commit/56fa4babb21d34d964f94a15a0783b309438a919
